#!/bin/bash

OutFil=background.xml
Statc=595.0
Trns=5.0
FilTyp="gif|jpg|png|bmp"
# SortFil=Alphabetic
SortFil=Random
Dpth=30 # at most levels of directories been include
# The line under here helps to setup the wallpaper automaticlly,
# comment it with octothorpe if you want do that yourself.
Autoset=on ; XmlFilPath=$HOME/.config


function find_image_files() {
  ImgFils=$(
            find -L $PWD \
                 -maxdepth $Dpth \
                 -regextype posix-extended \
                 -iregex \
                 ".*\.($FilTyp)" \
              2> /dev/null
           )

  if  [ "$SortFil" == "Random" ] ; then
    ImgFils=$( echo -e "$ImgFils" | sort -R )
  elif  [ "$SortFil" == "Alphabetic" ] ; then
    ImgFils=$( echo -e "$ImgFils" | sort )
  fi
}


function error_exit_if_too_less_image_file() {
  local filtol=$( echo -e "$ImgFils" \
                  | wc -l \
                  | cut -d " " -f1
                )

  if [ $filtol -lt 2 ] ; then
    /usr/bin/zenity --warning \
                    --title='Error!' \
                    --text='Need two image files at least!' \
          > /dev/null 2>&1
    echo -e '\nError!\nNeed two image files at least!\n'
    exit 1
  fi
}


find_image_files

error_exit_if_too_less_image_file

  eval $( date +"
                Yer=%Y
                Mnth=%m
                Day=%d
                Hour=%H
                Minute=%M
                Second=%S
         ")
  Head="  <static>\n    <duration>$Statc</duration>\n    <file>"
  Tail="</file>\n  </static>"
  FrmHead="  <transition>\n    <duration>$Trns</duration>\n    <from>"
  FrmTail="</from>"
  ToHead="    <to>"
  ToTail="</to>\n  </transition>"

  (
    echo "<background>"
    echo "  <starttime>"
    echo "    <year>$Yer</year>"
    echo "    <month>$Mnth</month>"
    echo "    <day>$Day</day>"
    echo "    <hour>$Hour</hour>"
    echo "    <minute>$Minute</minute>"
    echo "    <second>$Second</second>"
    echo "  </starttime>"
    echo "<!-- This animation starts at $Yer/$Mnth/$Day $Hour:$Minute:$Second. -->"

    if [ "$Trns" == "0" ] ; then
      echo -e "$ImgFils" | sed "s|^\(.*\)$|$Head\0$Tail|"
    else
      FstFil=$( echo -e "$ImgFils" | head -n 1 )
      echo -e "${Head}${FstFil}${Tail}"
      echo -e "${FrmHead}${FstFil}${FrmTail}"
      echo -e "$ImgFils" | tail -n +2 \
       | sed "s|^\(.*\)$|$ToHead\0$ToTail\n$Head\0$Tail\n$FrmHead\0$FrmTail|"
      echo -e "${ToHead}${FstFil}${ToTail}"
    fi

    echo "</background>"
  ) > "$OutFil"

  if [ "$Autoset" == "on" ] ; then
    if [ -z "$XmlFilPath" ] ; then
      XmlFilPath="$PWD"
    else
      mkdir -p "$XmlFilPath"
      mv -f "$OutFil" "$XmlFilPath/$OutFil"
    fi
    x=$(gnome-session --version)
    x=${x#* }
    if [ "${x%%.*}" == "3" ] ; then
      gsettings set org.gnome.desktop.background picture-uri "file://$XmlFilPath/$OutFil"
    elif [ "${x%%.*}" == "2" ] ; then
      gconftool --set --type=string /desktop/gnome/background/picture_filename "$XmlFilPath/$OutFil"
    fi
  fi

